//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_master
    {
        public int carId { get; set; }
        public int categoryId { get; set; }
        public string carName { get; set; }
        public string carModel { get; set; }
        public string carMake { get; set; }
        public int carDoors { get; set; }
        public int carSeats { get; set; }
        public Nullable<bool> carAC { get; set; }
        public string carType { get; set; }
        public int rentalCharge { get; set; }
        public string mileageAllowed { get; set; }
        public Nullable<bool> carStatus { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public string addedBy { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
    
        public virtual category_master category_master { get; set; }
    }
}
